# Generated by Django 5.0.7 on 2024-08-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biography',
            old_name='career',
            new_name='events',
        ),
        migrations.RemoveField(
            model_name='biography',
            name='personal_life',
        ),
    ]
