# Generated by Django 5.0.7 on 2024-08-19 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_rename_career_biography_events_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endorse',
            old_name='date',
            new_name='endorser_date',
        ),
        migrations.RenameField(
            model_name='endorse',
            old_name='endorsement_text',
            new_name='endorser_text',
        ),
    ]
