# Generated by Django 5.0.7 on 2024-08-21 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_alter_endorsement_candidate'),
        ('candidate', '0003_rename_date_endorse_endorser_date_and_more'),
    ]

    operations = [
    ]
