# Generated by Django 5.0.7 on 2024-08-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_biography_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='events',
            field=models.TextField(),
        ),
    ]
